var NavConstants = {
  WRITE_TOOLS_RENDERED: "WRITE_TOOLS_RENDERED",
  ARTICLE_SHOW_RENDERED: "ARTICLE_SHOW_RENDERED",
  DEFAULT_NAV_RENDERED: "DEFAULT_NAV_RENDERED",
  WRITE_TOOLS: "WRITE_TOOLS",
  ARTICLE_SHOW: "ARTICLE_SHOW",
  DEFAULT: "DEFAULT",
  DELETE_REQUESTED: "DELETE_REQUESTED",
  PUBLISH_REQUESTED: "PUBLISH_REQUESTED",
  DELETE_ARTICLE: "DELETE_ARTICLE",
  PUBLISH_ARTICLE: "PUBLISH_ARTICLE",
  SAVE_ARTICLE: "SAVE_ARTICLE",
};

module.exports = NavConstants;
