var NavConstants = {
  WRITE_TOOLS_RENDERED: "WRITE_TOOLS_RENDERED",
  ARTICLE_SHOW_RENDERED: "ARTICLE_SHOW_RENDERED",
  DEFAULT_NAV_RENDERED: "DEFAULT_NAV_RENDERED",
  WRITE_TOOLS: "WRITE_TOOLS",
  ARTICLE_SHOW: "ARTICLE_SHOW",
  DEFAULT: "DEFAULT"
};

module.exports = NavConstants;
