# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 236d51d0ce687b00506b25327f34ee2eda8996ed31f9f4c17c00b2ae51f730223ed790b99c2e3c905e732ac83ea851fd4f2e78891cd99aa702c192a2f53bdd75

test:
  secret_key_base: e31b805d1f22882a33a415ddb5f7e96e9f72d9e80669f01aa3eb833a4638a1123887a985727d0668af089f038f3371d7d5a0a65bb2c074560b47b351a7ec8d7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
